### ISSUE TITLE
prevent build breakages

### ISSUE THREAD

**Issue by anishkny** [netlify/staticgen#351]
Hi @biilmann @erquhart @eliwilliamson and team,

First up love what you guys are doing with [netlify/staticgen](https://github.com/netlify/staticgen) - big fan of the JAM stack!

In two previous PRs I made (#340, #348), builds broke ([1](https://app.netlify.com/sites/staticgen/deploys/5a9ffc1c92226a2a70ec5798), [2](https://app.netlify.com/sites/staticgen/deploys/5aae5e0ffd0efa69928f4168)) due to some repo moving and not related to the change I was making.

Since upstream dependencies (repos out of `staticgen`'s control) could break you, it would be nice to have some sort of cron build checker going on - it doesn't have to deploy, just ensure build does not break and open issue if it does.

Alternately, you could have a TravisCI project which allows daily cron builds but more frequent than daily would be better.

Not sure if this is already done - or on the cards?

**Comment by erquhart** [comment]
I believe the breakage is always due to a (re)moved GitHub repo, so the request results in a redirect or 404, and we break on both. We could just catch the error during the build, maybe print a warning, and keep moving.

This would still cause moved or removed repos to simply be excluded from the output, but I guess we could just check the build output every once in a while for those warning messages.

**Comment by erquhart** [comment]
Fixed in #411.
