### ISSUE TITLE
add orgmode-publish 

### ISSUE THREAD

**Issue by bhanuvrat** [netlify/staticgen#415]
https://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html

**Comment by dpflug** [comment]
Because org-mode isn't developed on GitHub, someone would need to adapt [the stats fetcher](https://github.com/netlify/staticgen/blob/master/scripts/fetch-archive.js) to support other repo types.

The primary way the projects are sorted is by GitHub stars. The number of stars on [orgmode's repo](https://code.orgmode.org/bzg/org-mode) isn't directly comparable, but I suppose it'll do.
